version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_client
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_client
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      DB_HOST: database
      DB_USER: db_client
      DB_PASSWORD: password
      DB_NAME: docker_doc_dev
    volumes:
      - ./src:/var/www/html

